-- Seed data: the original mock planets. Safe to re-run (upserts on slug).

insert into public.planets (
  slug, name, system, description, planet_type, controlling_faction,
  tithe_grade, population, climate, price_thrones, danger_level, travel_time,
  attractions, activities, active_conflicts, active_enemies, unit_factions
) values
  ('holy-terra', 'Holy Terra', 'Sol', 'The cradle of humanity and seat of the Imperium, Holy Terra is crowned by the Imperial Palace, where the Emperor sits upon the Golden Throne. Hive-cities sprawl across entire continents, and pilgrims from a million worlds queue for a glimpse of the divine. Expect crowds, incense and the most heavily guarded skies in the galaxy.', 'Throneworld', 'Adeptus Terra', 'Exactis Extremis', 'Over 20 billion', 'Polluted, continent-spanning hive-cities and mountain-sized palaces', 12000, 2, 'N/A (origin)',
   array['The Imperial Palace', 'The Golden Throne viewing gallery', 'Ecclesiarchy cathedrals']::text[],
   array['Pilgrimage walks', 'Guided Palace tours', 'Relic markets']::text[],
   array['Cult uprisings in the lower hives']::text[],
   array['Genestealer cults', 'Chaos infiltrators']::text[],
   array['Adeptus Custodes', 'Genestealer Cults']::text[]),
  ('cadia', 'Cadia', 'Cadian', 'A fortress world standing guard at the mouth of the Eye of Terror, Cadia raises its children to be soldiers and its cities to be bastions. Visitors can walk the great Kasr walls and learn why the Cadian Gate has held for so long. Travel here is for the stout of heart, and the sky is rarely quiet.', 'Fortress World', 'Astra Militarum', 'Solutio Extremis', 'Roughly 4 billion', 'Temperate, with harsh storms', 4500, 5, '6 weeks',
   array['Kasr fortress walls', 'Monument to the fallen']::text[],
   array['Military history tours', 'Live-fire demonstrations']::text[],
   array['Siege of the Cadian Gate']::text[],
   array['Black Legion', 'Chaos cultists']::text[],
   array['Astra Militarum', 'Chaos Space Marines']::text[]),
  ('macragge', 'Macragge', 'Macragge', 'Home of the Ultramarines and capital of the realm of Ultramar, Macragge is among the most orderly and prosperous worlds in the Imperium. Mild coastal plains give way to snowy highlands, all watched over by the Fortress of Hera. A refined destination for travellers who prefer discipline, history and clean streets.', 'Civilised World', 'Ultramarines', 'Decuma Particular', 'Around 3 billion', 'Mild coastal plains and snowy highlands', 6800, 3, '5 weeks',
   array['Fortress of Hera', 'Hall of Heroes']::text[],
   array['Honour-guard parade viewing', 'Highland trekking']::text[],
   array['Skirmishes along the Ultramar border']::text[],
   array['Tyranid splinter fleets']::text[],
   array['Ultramarines', 'Tyranids']::text[]),
  ('fenris', 'Fenris', 'Fenris', 'A frozen death world of ice, storms and shifting glaciers, Fenris is the home of the Space Wolves and the great fortress-monastery of the Fang. Its people are proud, boisterous and fiercely hospitable to guests who can keep up with the feasting. Pack warm, respect the sagas and do not wander from the hall at night.', 'Death World', 'Space Wolves', 'Aptus Non', 'Sparse tribal settlements', 'Arctic, with perpetual storms and shifting ice', 3200, 4, '4 weeks',
   array['The Fang', 'Aett of the Wolf Kings']::text[],
   array['Frost-beast hunts', 'Sagas around the great hall fires']::text[],
   array['Wolf-clan feuds']::text[],
   array['Thousand Sons raiders']::text[],
   array['Space Wolves', 'Thousand Sons']::text[]),
  ('armageddon', 'Armageddon', 'Armageddon', 'An industrial hive world of vast factories, towering spires and endless ash wastes, Armageddon builds the weapons that win the Emperor''s wars. Its hives, Infernus among them, hum day and night with the labour of billions. The planet has endured wave after wave of invasion, and the scars make for sobering sightseeing.', 'Hive World', 'Imperial Governor / Astra Militarum', 'Exactis Particular', 'Over 10 billion', 'Ash wastes and acidic rains', 2900, 4, '7 weeks',
   array['Hive Infernus', 'The Ash Wastes overlook']::text[],
   array['Factory tours', 'Ork-hunting excursions']::text[],
   array['Third War for Armageddon']::text[],
   array['Ork WAAAGH! Ghazghkull', 'Daemons']::text[],
   array['Astra Militarum', 'Orks']::text[]),
  ('catachan', 'Catachan', 'Catachan', 'A lethal jungle death world where nearly every plant, beast and insect is hunting something, Catachan forges the toughest soldiers in the Imperial Guard. Guided treks reach the high canopy and the strange sentient gardens, though survival is not included in the price. Recommended only for the adventurous, the insured and the very well armed.', 'Death World', 'Catachan Jungle Fighters', 'Aptus Non', 'Sparse, scattered tribes', 'Dense, carnivorous jungle', 2100, 5, '8 weeks',
   array['Devil''s Reach canopy', 'Sentient flora gardens']::text[],
   array['Survival trek', 'Wildlife safari (no refunds)']::text[],
   array['Ongoing predator culls']::text[],
   array['Tyranid scouts', 'Hostile megafauna']::text[],
   array['Astra Militarum', 'Tyranids']::text[])
on conflict (slug) do update set
  name = excluded.name,
  system = excluded.system,
  description = excluded.description,
  planet_type = excluded.planet_type,
  controlling_faction = excluded.controlling_faction,
  tithe_grade = excluded.tithe_grade,
  population = excluded.population,
  climate = excluded.climate,
  price_thrones = excluded.price_thrones,
  danger_level = excluded.danger_level,
  travel_time = excluded.travel_time,
  attractions = excluded.attractions,
  activities = excluded.activities,
  active_conflicts = excluded.active_conflicts,
  active_enemies = excluded.active_enemies,
  unit_factions = excluded.unit_factions;
